name: Playwright TS E2E tests

on:
  push:
    branches:
      - never
  pull_request:
      types:
        - opened
        - edited
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run Playwright TS E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx bddgen && npx playwright test --reporter=html --config=playwright.config.ts
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          BASE_API_URL: ${{ vars.BASE_API_URL }}
      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-artifacts
          path: |
            playwright-report/
          retention-days: 14